<?php

/**
 * @file
 * Contains cryo_seaice_bokeh.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cryo_seaice_bokeh_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
    // Main module help for the cryo_seaice_bokeh module.
    case 'help.page.cryo_seaice_bokeh':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bokeh SeaIce visualization for CRYO') . '</p>';
      return $output;

    default:
  }
}


function cryo_seaice_bokeh_theme_suggestions_page(array $variables)
{
    $path = explode('/', trim(\Drupal::service('path.current')->getPath(), '/'));
    if (isset($path[0]) && $path[0] == 'bokeh') {
        if (isset($path[1]) && $path[1] == 'seaice') {
            return 'page__cryo_seaice_bokeh';
        }
    }
}

/**
 * Implements hook_theme().
 */
function cryo_seaice_bokeh_theme($existing, $type, $theme, $path)
{
    return [
    'page__cryo_seaice_bokeh' => [
      //'base hook' => 'page',
      'variables' => array('test_var' => null),
      'template' => 'page--cryo-seaice-bokeh',
    ],
  ];
}
